// Hand-curated SUBSET of the codex app-server protocol — only the messages this spike uses.
// The full, authoritative types are machine-generated by the binary:
//   codex app-server generate-ts --out <dir>
//   codex app-server generate-json-schema --out <dir>
// Regenerate and reconcile when bumping the Codex version. Verified: codex-cli 0.144.1.

export type RequestId = string | number;

/** Wire envelopes (NDJSON, one JSON object per line). NOT JSON-RPC 2.0. */
export interface WireClientRequest {
  id: RequestId;
  method: string;
  params?: unknown;
}
export interface WireClientNotification {
  method: string;
  params?: unknown;
}
/** A response to one of OUR requests: has id + (result | error), no method. */
export interface WireResponse {
  id: RequestId;
  result?: unknown;
  error?: { code?: number; message?: string; data?: unknown };
}
/** A server-INITIATED request (e.g. an approval): has BOTH id and method. */
export interface WireServerRequest {
  id: RequestId;
  method: string;
  params: unknown;
}
/** A server notification (streaming event): has method, no id. */
export interface WireServerNotification {
  method: string;
  params: unknown;
}

// ---- initialize ----
export interface ClientInfo {
  name: string;
  title?: string | null;
  version: string;
}
export interface InitializeParams {
  clientInfo: ClientInfo;
  capabilities: {
    experimentalApi: boolean;
    requestAttestation: boolean;
    mcpServerOpenaiFormElicitation?: boolean;
    optOutNotificationMethods?: string[] | null;
  } | null;
}
export interface InitializeResponse {
  userAgent: string;
  codexHome: string;
  platformFamily: string;
  platformOs: string;
}

// ---- thread / turn ----
export type SandboxMode = "read-only" | "workspace-write" | "danger-full-access";
export type AskForApproval = "untrusted" | "on-request" | "never";

export interface ThreadStartParams {
  cwd?: string | null;
  approvalPolicy?: AskForApproval | null;
  sandbox?: SandboxMode | null;
  model?: string | null;
}
/** Minimal view of the Thread object we care about in the spike. */
export interface Thread {
  id: string;
  cwd: string;
  model?: string | null;
  status?: unknown;
  path?: string | null;
}
export interface ThreadStartResult {
  thread: Thread;
  model?: string;
  runtimeWorkspaceRoots?: string[];
  instructionSources?: string[];
  approvalPolicy?: string;
  sandbox?: unknown;
}

export type UserInput =
  | { type: "text"; text: string; text_elements: unknown[] }
  | { type: "image"; url: string }
  | { type: "localImage"; path: string };

export interface TurnStartParams {
  threadId: string;
  input: UserInput[];
  clientUserMessageId?: string | null;
}
export interface TurnInterruptParams {
  threadId: string;
  turnId: string;
}
export interface ThreadResumeParams {
  threadId: string;
  cwd?: string | null;
}
export interface ThreadListParams {
  limit?: number | null;
  cwd?: string | string[] | null;
}

// ---- streaming notification params (the subset we render) ----
export interface AgentMessageDeltaParams {
  threadId: string;
  turnId: string;
  itemId: string;
  delta: string;
}
export interface ItemLifecycleParams {
  item: { type: string; id: string; [k: string]: unknown };
  threadId: string;
  turnId: string;
}
export interface TurnLifecycleParams {
  threadId: string;
  turn: { id: string; status?: unknown };
}

// ---- approvals (server -> client requests) ----
/** Decision the client sends back. The valid set is dictated per-request by the server's
 *  `availableDecisions`; we never invent a decision the server did not offer. */
export type CommandExecutionApprovalDecision =
  | "accept"
  | "acceptForSession"
  | "decline"
  | "cancel"
  | { acceptWithExecpolicyAmendment: { execpolicy_amendment: unknown } };

export interface CommandExecutionRequestApprovalParams {
  threadId: string;
  turnId: string;
  itemId: string;
  command?: string | null;
  cwd?: string | null;
  reason?: string | null;
  availableDecisions?: unknown[];
}
