// Hand-curated SUBSET of the codex app-server protocol — only the messages the adapter consumes
// or produces. The full, authoritative types are machine-generated by the binary:
//   codex app-server generate-ts --experimental --out <dir>
// Regenerate and reconcile when bumping the Codex version. Verified: codex-cli 0.144.1.
// The decision enums below are copied VERBATIM from that generated output — see
// docs/design/codex-approval-matrix.md for provenance + the live-capture that proved them.
//
// IMPORTANT: two parallel approval systems exist. This adapter uses the **v2** thread/turn API
// (`item/*/requestApproval`, `item/tool/requestUserInput`), NOT the legacy v1
// (`execCommandApproval`/`applyPatchApproval` with the different `ReviewDecision` enum).

export type RequestId = string | number;

// ---- wire envelopes (NDJSON, one JSON object per line). NOT JSON-RPC 2.0. ----
export interface WireClientRequest {
  id: RequestId;
  method: string;
  params?: unknown;
}
export interface WireClientNotification {
  method: string;
  params?: unknown;
}
/** A response to one of OUR requests: has id + (result | error), no method. */
export interface WireResponse {
  id: RequestId;
  result?: unknown;
  error?: { code?: number; message?: string; data?: unknown };
}
/** A server-INITIATED request (e.g. an approval): has BOTH id and method. */
export interface WireServerRequest {
  id: RequestId;
  method: string;
  params: unknown;
}
/** A server notification (streaming event): has method, no id. */
export interface WireServerNotification {
  method: string;
  params: unknown;
}

// ---- initialize ----
export interface ClientInfo {
  name: string;
  title?: string | null;
  version: string;
}
export interface InitializeParams {
  clientInfo: ClientInfo;
  capabilities: {
    experimentalApi: boolean;
    requestAttestation: boolean;
    mcpServerOpenaiFormElicitation?: boolean;
    optOutNotificationMethods?: string[] | null;
  } | null;
}
export interface InitializeResponse {
  userAgent: string;
  codexHome: string;
  platformFamily: string;
  platformOs: string;
}

// ---- thread / turn ----
export type SandboxMode = "read-only" | "workspace-write" | "danger-full-access";
export type AskForApproval = "untrusted" | "on-request" | "never";

export interface ThreadStartParams {
  cwd?: string | null;
  approvalPolicy?: AskForApproval | null;
  sandbox?: SandboxMode | null;
  model?: string | null;
}
/** Minimal view of the Thread object we care about. */
export interface Thread {
  id: string;
  cwd: string;
  model?: string | null;
  status?: unknown;
  path?: string | null;
}
export interface ThreadStartResult {
  thread: Thread;
  model?: string;
  runtimeWorkspaceRoots?: string[];
  instructionSources?: string[];
  approvalPolicy?: string;
  sandbox?: unknown;
}

export type UserInput =
  | { type: "text"; text: string; text_elements: unknown[] }
  | { type: "image"; url: string }
  | { type: "localImage"; path: string };

export interface TurnStartParams {
  threadId: string;
  input: UserInput[];
  clientUserMessageId?: string | null;
}
export interface TurnInterruptParams {
  threadId: string;
  turnId: string;
}
export interface ThreadResumeParams {
  threadId: string;
  cwd?: string | null;
}
export interface ThreadListParams {
  limit?: number | null;
  cwd?: string | string[] | null;
}

/** Convenience: build the `input` for a plain-text user turn. */
export function textInput(text: string): UserInput[] {
  return [{ type: "text", text, text_elements: [] }];
}

// ---- streaming notification params (the subset we render) ----
export interface AgentMessageDeltaParams {
  threadId: string;
  turnId: string;
  itemId: string;
  delta: string;
}
export interface ItemLifecycleParams {
  item: { type: string; id: string; [k: string]: unknown };
  threadId: string;
  turnId: string;
}
export interface TurnLifecycleParams {
  threadId: string;
  turn: { id: string; status?: unknown };
}

// ---- v2 approvals: server -> client requests (method names) ----
export const SERVER_REQUEST_METHODS = {
  commandApproval: "item/commandExecution/requestApproval",
  fileChangeApproval: "item/fileChange/requestApproval",
  requestUserInput: "item/tool/requestUserInput",
  permissionsApproval: "item/permissions/requestApproval",
  elicitation: "mcpServer/elicitation/request",
} as const;

// ---- v2 decision enums (VERBATIM from generated types — do not paraphrase) ----

/** `item/commandExecution/requestApproval` response is `{ decision: CommandExecutionApprovalDecision }`.
 *  A list of these arrives in the request's `availableDecisions`. */
export type CommandExecutionApprovalDecision =
  | "accept"
  | "acceptForSession"
  | { acceptWithExecpolicyAmendment: { execpolicy_amendment: string[] } }
  | { applyNetworkPolicyAmendment: { network_policy_amendment: unknown } }
  | "decline"
  | "cancel";

/** `item/fileChange/requestApproval` transmits NO `availableDecisions`; this fixed set IS the
 *  protocol contract (generated `FileChangeApprovalDecision`). Response is `{ decision }`. */
export type FileChangeApprovalDecision = "accept" | "acceptForSession" | "decline" | "cancel";

/** The protocol-fixed fileChange option set, in display order. There is no wire list to read, so
 *  the adapter surfaces this constant — faithful because it is the generated enum, not invented. */
export const FILE_CHANGE_DECISIONS: readonly FileChangeApprovalDecision[] = [
  "accept",
  "acceptForSession",
  "decline",
  "cancel",
];

// ---- v2 approval request params (subset we consume) ----
export interface CommandExecutionRequestApprovalParams {
  threadId: string;
  turnId: string;
  itemId: string;
  startedAtMs: number;
  approvalId?: string | null;
  reason?: string | null;
  command?: string | null;
  cwd?: string | null;
  /** Ordered list of decisions the client may present for this prompt. */
  availableDecisions?: CommandExecutionApprovalDecision[] | null;
}
export interface FileChangeRequestApprovalParams {
  threadId: string;
  turnId: string;
  itemId: string;
  startedAtMs: number;
  reason?: string | null;
  grantRoot?: string | null;
}

// ---- v2 requestUserInput (EXPERIMENTAL — types known, not yet fired live) ----
export interface ToolRequestUserInputOption {
  label: string;
  description: string;
}
export interface ToolRequestUserInputQuestion {
  id: string;
  header: string;
  question: string;
  isOther: boolean;
  isSecret: boolean;
  options: ToolRequestUserInputOption[] | null;
}
export interface ToolRequestUserInputParams {
  threadId: string;
  turnId: string;
  itemId: string;
  questions: ToolRequestUserInputQuestion[];
  autoResolutionMs: number | null;
}
/** Response payload: one answer entry per question id; each answer is a list of strings. */
export interface ToolRequestUserInputResponse {
  answers: { [questionId: string]: { answers: string[] } };
}
